algo: sarsa
envparameters:
  action_continuous: false
  action_space: 4
  n_player: 1
  obs_continuous: true
  obs_space: 48
  scenario: cliffwalking
hyperparameters:
  buffer_capacity: 1
  epsilon: 0.2
  epsilon_end: 0.01
  gamma: 0.9
  learn_freq: 1
  learn_terminal: false
  lr: 0.1
  marl: false
  use_network: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 1000
  render: true
  save_interval: 100
