algo: duelingq
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  batch_size: 64
  buffer_capacity: 1024
  c_lr: 0.005
  epsilon: 0.5
  epsilon_end: 0.05
  gamma: 0.99
  hidden_size: 64
  learn_freq: 1
  learn_terminal: false
  marl: false
  target_replace: 100
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 500
  render: false
  save_interval: 500
